name: .NET

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ main, Development ]

jobs:
  build:
    name: build to development
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://github.com/Jangerud/CI-Uppgift1/tree/Development

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --verbosity normal
      
  production:
    if: github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/Jangerud/CI-Uppgift1/tree/main
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
   
